import type { Metadata } from "next";
import { Inter  as FontSans } from "next/font/google"
import { cn } from "@/lib/utils";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-providers";


const fontSans = FontSans({ 
  subsets: ["latin"], 
  variable: "--font-sans"
});

export const metadata: Metadata = {
  title: "LLama-3-8B",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('min-h-screen font-sans antialiased', fontSans.variable)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
